// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgaclOBZQvPQzgB-xiYhZO3WnXB1hZKmY',
    appId: '1:458912438306:android:09b4efca902a32750c127b',
    messagingSenderId: '458912438306',
    projectId: 'fir-firebase-emulator',
    databaseURL: 'https://fir-firebase-emulator-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-firebase-emulator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjsOOqVZX_MTq2u8LV8Yd2AOPm79VSfUA',
    appId: '1:458912438306:ios:a31471064f72ea900c127b',
    messagingSenderId: '458912438306',
    projectId: 'fir-firebase-emulator',
    databaseURL: 'https://fir-firebase-emulator-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-firebase-emulator.appspot.com',
    iosClientId: '458912438306-6499vjq7armt6ac3o207lt7jsuba38se.apps.googleusercontent.com',
    iosBundleId: 'com.example.authWithFirebaseSimulator',
  );
}
